# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: MultiSenS
subtitle: Cefet/RJ
# description: >- # this means to ignore newlines until "baseurl:"
#   Write an awesome description for your new site here. You can edit this
#   line in _config.yml. It will appear in your document head meta (for
#   Google search results) and in your feed.xml site description.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://multisens.com.br" # the base hostname & protocol for your site, e.g. http://example.com


# social settings (key must match name of font awesome icon)
# see https://fontawesome.com/icons?d=gallery&p=2&s=brands
# Icons are not shown if value is empty
# You need to restart jekyll for changes to have an effect
socials:
  GitHub: https://github.com/multisens
  YouTube: https://www.youtube.com/@multisens
  Itch-io: https://itch.io/profile/gpmm

# partners to present at home
partners:
  midiacom:
    logo: assets/images/logo-midiacom.png
    name: "Laboratório Mídiacom"
    url: https://www.midiacom-uff.com.br
  buglab:
    logo: assets/images/bug-lab.png
    name: "Bug Lab"
  great:
    logo: assets/images/logo-great-peq.png
    name: "GREat"
    url: https://www.great.ufc.br
  limno:
    logo: assets/images/logo-limno.png
    name: "Laboratório de Limnologia da UFRJ"
    url: http://www.intranet.biologia.ufrj.br/limnologia

# Project pages
collections:
  projects:
    output: true
    permalink: /projetos/:name

# Build settings
markdown: kramdown
sass:
  style: compressed

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
  - "*.gemspec"
#   - LICENSE.md
#   - README.md
  - "xxx*" 
